apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 01-discoveryserver.yaml
  - 02-postgres.yaml
  - 03-redis.yaml
  - 04-kafka.yaml
  - 05-configserver.yaml
  - 06-user-service.yaml
  - 07-job-service.yaml
  - 08-matching-service.yaml
  - 09-notification-service.yaml
  - 10-gatewayserver.yaml
  - 11-gateway-nodeport.yaml
